const SAVE_OPTIONS = { IPFS: "ipfs", DOWNLOADS: "downloads", BOTH: "both" };
const MESSAGE_TYPES = {
  SCRAPE: "SCRAPE",
  HTML: "HTML",
  PDF_WITH_SAVED_METADATA: "PDF_WITH_SAVED_METADATA",
  PDF_WITHOUT_SAVED_METADATA: "PDF_WITHOUT_SAVED_METADATA",
  DETAILS: "DETAILS",
  ERROR: "ERROR",
};

export { SAVE_OPTIONS, MESSAGE_TYPES };
