const SAVE_OPTIONS = { IPFS: "ipfs", DOWNLOADS: "downloads", BOTH: "both" };
const MESSAGE_TYPES = {
  START_SCRAPE: "START_SCRAPE",
  HTML: "HTML",
  NEW_TAB_PDF: "NEW_TAB_PDF",
  ACTIVE_TAB_PDF: "ACTIVE_TAB_PDF",
  ERROR: "ERROR",
};

export { SAVE_OPTIONS, MESSAGE_TYPES };
